<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BgIntercom\Module'                => __DIR__ . '/Module.php',
    'BgIntercom\Options\ModuleOptions' => __DIR__ . '/src/BgIntercom/Options/ModuleOptions.php',
    'BgIntercom\View\Helper\Intercom'  => __DIR__ . '/src/BgIntercom/View/Helper/Intercom.php',
);